#!/usr/bin/env python3
"""
SFC to MATIEC Converter - Fixed Version
Usage: python sfc_converter.py <your_sfc_file.txt>
"""

import subprocess
import sys
import os

class SFCConverter:
    def __init__(self, sfc_file):
        self.sfc_file  = sfc_file
        self.steps       = []
        self.transitions = []
        self.variables   = []
        self.initial_step = None
        self.st_lines    = []   # list of strings, joined with \n at the end

    # ------------------------------------------------------------------ #
    #  STEP 1  Parse the SFC text file                                   #
    # ------------------------------------------------------------------ #
    def parse(self):
        print("\n[STEP 1] Parsing SFC file: {}".format(self.sfc_file))
        try:
            with open(self.sfc_file, 'r') as f:
                src = f.read()
            ns = {}
            exec(compile(src, self.sfc_file, 'exec'), {}, ns)
            self.steps        = ns.get('steps',        [])
            self.transitions  = ns.get('transitions',  [])
            self.variables    = ns.get('variables',    [])
            self.initial_step = ns.get('initial_step', None)
            print("   Steps       : {}".format(len(self.steps)))
            print("    Transitions : {}".format(len(self.transitions)))
            print("    Variables   : {}".format(len(self.variables)))
            print("    Initial step: {}".format(self.initial_step))
            return True
        except Exception as e:
            print("   Parse ERROR : {}".format(e))
            return False

    # ------------------------------------------------------------------ #
    #  STEP 2  Generate IEC 61131-3 Structured Text                      #
    # ------------------------------------------------------------------ #
    def generate(self):
        print("\n[STEP 2] Generating Structured Text (ST) code ...")
        L = self.st_lines
        L.clear()

        L.append("PROGRAM SFC_Program")
        L.append("(* Auto-generated by sfc_converter.py *)")
        L.append("")
        L.append("VAR")

        # step flags
        for s in self.steps:
            L.append("  {}_active : BOOL := FALSE;".format(s['name']))

        # user variables
        for v in self.variables:
            if isinstance(v, dict):
                vname = v.get('name', str(v))
                vtype = v.get('type', 'BOOL')
            else:
                vname = str(v)
                vtype = 'BOOL'
            init = "0" if vtype in ('INT','DINT','REAL') else "FALSE"
            L.append("  {} : {} := {};".format(vname, vtype, init))

        L.append("END_VAR")
        L.append("")

        # Initialise initial step on first scan
        L.append("(* --- Initialise initial step --- *)")
        L.append("IF NOT {}_active THEN".format(self.initial_step))
        L.append("  {}_active := TRUE;".format(self.initial_step))
        L.append("END_IF;")
        L.append("")

        # Transitions
        L.append("(* --- Transitions --- *)")
        for t in self.transitions:
            src   = t.get('src',   'UNKNOWN')
            tgt   = t.get('tgt',   'UNKNOWN')
            guard = str(t.get('guard', 'TRUE')).strip() or 'TRUE'
            L.append("IF {}_active AND ({}) THEN".format(src, guard))
            L.append("  {}_active := FALSE;".format(src))
            L.append("  {}_active := TRUE;".format(tgt))
            L.append("END_IF;")

        L.append("")
        L.append("END_PROGRAM")
        print("    {} lines of ST code generated.".format(len(L)))

    # ------------------------------------------------------------------ #
    #  STEP 3  Save .st file                                             #
    # ------------------------------------------------------------------ #
    def save(self, out_file):
        print("\n[STEP 3] Saving ST file: {}".format(out_file))
        try:
            with open(out_file, 'w') as f:
                f.write("\n".join(self.st_lines))
            print("    File saved successfully.")
            return True
        except Exception as e:
            print("   Save ERROR : {}".format(e))
            return False

    # ------------------------------------------------------------------ #
    #  STEP 4  Compile with MATIEC                                       #
    # ------------------------------------------------------------------ #
    def compile(self, st_file):
        print("\n[STEP 4] Attempting MATIEC compilation ...")

        # Check MATIEC presence
        check = subprocess.run(['which', 'matiec'],
                               capture_output=True, text=True)
        if check.returncode != 0:
            print("  ! MATIEC compiler NOT found on this system.")
            print("    Install it: sudo apt-get install matiec")
            print("    Falling back to built-in syntax check ...\n")
            return self._syntax_check(st_file)

        # Run MATIEC
        result = subprocess.run(['matiec', '-c', st_file],
                                capture_output=True, text=True, timeout=30)
        if result.returncode == 0:
            return True, "MATIEC compilation successful."
        else:
            err = result.stderr.strip() or result.stdout.strip()
            return False, err

    # ------------------------------------------------------------------ #
    #  Built-in syntax checker (used when MATIEC is absent)               #
    # ------------------------------------------------------------------ #
    def _syntax_check(self, st_file):
        errors = []
        with open(st_file, 'r') as f:
            code = f.read()

        # keyword balance checks
        pairs = [
            ('PROGRAM',  'END_PROGRAM'),
            ('VAR',      'END_VAR'),
            ('IF',       'END_IF'),
            ('FOR',      'END_FOR'),
            ('WHILE',    'END_WHILE'),
            ('CASE',     'END_CASE'),
        ]
        for kw_open, kw_close in pairs:
            cnt_open  = len([l for l in code.split('\n')
                             if l.strip().startswith(kw_open)])
            cnt_close = code.count(kw_close)
            if cnt_open != cnt_close:
                errors.append("  Mismatched {} / {}  (found {} open, {} close)"
                              .format(kw_open, kw_close, cnt_open, cnt_close))

        # semicolons at end of assignments
        assign_lines = [l.strip() for l in code.split('\n')
                        if ':=' in l and not l.strip().startswith('(*')]
        for line in assign_lines:
            if not line.endswith(';'):
                errors.append("  Missing semicolon: {}".format(line))

        if errors:
            return False, "\n".join(errors)
        return True, "Built-in syntax check PASSED (no obvious errors found)."

    # ------------------------------------------------------------------ #
    #  Main pipeline                                                      #
    # ------------------------------------------------------------------ #
    def run(self, out_file=None):
        print("=" * 60)
        print("     MATIEC  Conversion Pipeline")
        print("=" * 60)

        if not self.parse():
            self._result("FAILED", "Could not parse SFC file.")
            return False

        self.generate()

        if out_file is None:
            base     = os.path.splitext(self.sfc_file)[0]
            out_file = base + ".st"

        if not self.save(out_file):
            self._result("FAILED", "Could not save ST file.")
            return False

        ok, msg = self.compile(out_file)

        print("\n" + "=" * 60)
        if ok:
            print("  COMPILATION RESULT :  -->  SUCCESS")
            print("=" * 60)
            print("  {}".format(msg))
        else:
            print("  COMPILATION RESULT :  -->  FAILED")
            print("=" * 60)
            print("  Error details:\n{}".format(msg))
        print("=" * 60)

        # Always print generated code so user can see it
        print("\n--- Generated ST Code ({}) ---".format(out_file))
        print("\n".join(self.st_lines))
        print("--- End of ST Code ---\n")
        return ok

    @staticmethod
    def _result(status, msg):
        print("\n" + "=" * 60)
        print("  RESULT : {}".format(status))
        print("=" * 60)
        print("  {}".format(msg))
        print("=" * 60)


# ------------------------------------------------------------------ #
#  Entry point                                                        #
# ------------------------------------------------------------------ #
def main():
    if len(sys.argv) < 2:
        print("""
Usage:
  python sfc_converter.py <sfc_file.txt> [output.st]

Examples:
  python sfc_converter.py traffic_light.txt
  python sfc_converter.py traffic_light.txt out/traffic.st

SFC File Format:
  steps       = [ { "name": "S1", "function": "F1" }, ... ]
  transitions = [ { "src": "S1", "tgt": "S2", "guard": "Cond" }, ... ]
  variables   = [ { "name": "var1", "type": "BOOL" }, ... ]
  initial_step = "S1"
""")
        sys.exit(1)

    sfc_file = sys.argv[1]
    out_file = sys.argv[2] if len(sys.argv) > 2 else None

    if not os.path.exists(sfc_file):
        print("[ERROR] File not found: {}".format(sfc_file))
        sys.exit(1)

    ok = SFCConverter(sfc_file).run(out_file)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
