# #!/usr/bin/env python3
# """
# SFC to MATIEC Converter - Fixed Version
# Usage: python sfc_converter.py <your_sfc_file.txt>
# """

# import subprocess
# import sys
# import os

# class SFCConverter:
#     def __init__(self, sfc_file):
#         self.sfc_file  = sfc_file
#         self.steps       = []
#         self.transitions = []
#         self.variables   = []
#         self.initial_step = None
#         self.st_lines    = []   # list of strings, joined with \n at the end

#     # ------------------------------------------------------------------ #
#     #  STEP 1  Parse the SFC text file                                   #
#     # ------------------------------------------------------------------ #
#     def parse(self):
#         print("\n[STEP 1] Parsing SFC file: {}".format(self.sfc_file))
#         try:
#             with open(self.sfc_file, 'r') as f:
#                 src = f.read()
#             ns = {}
#             exec(compile(src, self.sfc_file, 'exec'), {}, ns)
#             self.steps        = ns.get('steps',        [])
#             self.transitions  = ns.get('transitions',  [])
#             self.variables    = ns.get('variables',    [])
#             self.initial_step = ns.get('initial_step', None)
#             print("   Steps       : {}".format(len(self.steps)))
#             print("    Transitions : {}".format(len(self.transitions)))
#             print("    Variables   : {}".format(len(self.variables)))
#             print("    Initial step: {}".format(self.initial_step))
#             return True
#         except Exception as e:
#             print("   Parse ERROR : {}".format(e))
#             return False

#     # ------------------------------------------------------------------ #
#     #  STEP 2  Generate IEC 61131-3 Structured Text                      #
#     # ------------------------------------------------------------------ #
#     def generate(self):
#         print("\n[STEP 2] Generating Structured Text (ST) code ...")
#         L = self.st_lines
#         L.clear()

#         L.append("PROGRAM SFC_Program")
#         L.append("(* Auto-generated by sfc_converter.py *)")
#         L.append("")
#         L.append("VAR")

#         # step flags
#         for s in self.steps:
#             L.append("  {}_active : BOOL := FALSE;".format(s['name']))

#         # user variables
#         for v in self.variables:
#             if isinstance(v, dict):
#                 vname = v.get('name', str(v))
#                 vtype = v.get('type', 'BOOL')
#             else:
#                 vname = str(v)
#                 vtype = 'BOOL'
#             init = "0" if vtype in ('INT','DINT','REAL') else "FALSE"
#             L.append("  {} : {} := {};".format(vname, vtype, init))

#         L.append("END_VAR")
#         L.append("")

#         # Initialise initial step on first scan
#         L.append("(* --- Initialise initial step --- *)")
#         L.append("IF NOT {}_active THEN".format(self.initial_step))
#         L.append("  {}_active := TRUE;".format(self.initial_step))
#         L.append("END_IF;")
#         L.append("")

#         # Transitions
#         L.append("(* --- Transitions --- *)")
#         for t in self.transitions:
#             src   = t.get('src',   'UNKNOWN')
#             tgt   = t.get('tgt',   'UNKNOWN')
#             guard = str(t.get('guard', 'TRUE')).strip() or 'TRUE'
#             L.append("IF {}_active AND ({}) THEN".format(src, guard))
#             L.append("  {}_active := FALSE;".format(src))
#             L.append("  {}_active := TRUE;".format(tgt))
#             L.append("END_IF;")

#         L.append("")
#         L.append("END_PROGRAM")
#         print("    {} lines of ST code generated.".format(len(L)))

#     # ------------------------------------------------------------------ #
#     #  STEP 3  Save .st file                                             #
#     # ------------------------------------------------------------------ #
#     def save(self, out_file):
#         print("\n[STEP 3] Saving ST file: {}".format(out_file))
#         try:
#             with open(out_file, 'w') as f:
#                 f.write("\n".join(self.st_lines))
#             print("    File saved successfully.")
#             return True
#         except Exception as e:
#             print("   Save ERROR : {}".format(e))
#             return False

#     # ------------------------------------------------------------------ #
#     #  STEP 4  Compile with MATIEC                                       #
#     # ------------------------------------------------------------------ #
#     def compile(self, st_file):
#         print("\n[STEP 4] Attempting MATIEC compilation ...")

#         # Check MATIEC presence
#         check = subprocess.run(['which', 'matiec'],
#                                capture_output=True, text=True)
#         if check.returncode != 0:
#             print("  ! MATIEC compiler NOT found on this system.")
#             print("    Install it: sudo apt-get install matiec")
#             print("    Falling back to built-in syntax check ...\n")
#             return self._syntax_check(st_file)

#         # Run MATIEC
#         result = subprocess.run(['matiec', '-c', st_file],
#                                 capture_output=True, text=True, timeout=30)
#         if result.returncode == 0:
#             return True, "MATIEC compilation successful."
#         else:
#             err = result.stderr.strip() or result.stdout.strip()
#             return False, err

#     # ------------------------------------------------------------------ #
#     #  Built-in syntax checker (used when MATIEC is absent)               #
#     # ------------------------------------------------------------------ #
#     def _syntax_check(self, st_file):
#         errors = []
#         with open(st_file, 'r') as f:
#             code = f.read()

#         # keyword balance checks
#         pairs = [
#             ('PROGRAM',  'END_PROGRAM'),
#             ('VAR',      'END_VAR'),
#             ('IF',       'END_IF'),
#             ('FOR',      'END_FOR'),
#             ('WHILE',    'END_WHILE'),
#             ('CASE',     'END_CASE'),
#         ]
#         for kw_open, kw_close in pairs:
#             cnt_open  = len([l for l in code.split('\n')
#                              if l.strip().startswith(kw_open)])
#             cnt_close = code.count(kw_close)
#             if cnt_open != cnt_close:
#                 errors.append("  Mismatched {} / {}  (found {} open, {} close)"
#                               .format(kw_open, kw_close, cnt_open, cnt_close))

#         # semicolons at end of assignments
#         assign_lines = [l.strip() for l in code.split('\n')
#                         if ':=' in l and not l.strip().startswith('(*')]
#         for line in assign_lines:
#             if not line.endswith(';'):
#                 errors.append("  Missing semicolon: {}".format(line))

#         if errors:
#             return False, "\n".join(errors)
#         return True, "Built-in syntax check PASSED (no obvious errors found)."

#     # ------------------------------------------------------------------ #
#     #  Main pipeline                                                      #
#     # ------------------------------------------------------------------ #
#     def run(self, out_file=None):
#         print("=" * 60)
#         print("     MATIEC  Conversion Pipeline")
#         print("=" * 60)

#         if not self.parse():
#             self._result("FAILED", "Could not parse SFC file.")
#             return False

#         self.generate()

#         if out_file is None:
#             base     = os.path.splitext(self.sfc_file)[0]
#             out_file = base + ".st"

#         if not self.save(out_file):
#             self._result("FAILED", "Could not save ST file.")
#             return False

#         ok, msg = self.compile(out_file)

#         print("\n" + "=" * 60)
#         if ok:
#             print("  COMPILATION RESULT :  -->  SUCCESS")
#             print("=" * 60)
#             print("  {}".format(msg))
#         else:
#             print("  COMPILATION RESULT :  -->  FAILED")
#             print("=" * 60)
#             print("  Error details:\n{}".format(msg))
#         print("=" * 60)

#         # Always print generated code so user can see it
#         print("\n--- Generated ST Code ({}) ---".format(out_file))
#         print("\n".join(self.st_lines))
#         print("--- End of ST Code ---\n")
#         return ok

#     @staticmethod
#     def _result(status, msg):
#         print("\n" + "=" * 60)
#         print("  RESULT : {}".format(status))
#         print("=" * 60)
#         print("  {}".format(msg))
#         print("=" * 60)


# # ------------------------------------------------------------------ #
# #  Entry point                                                        #
# # ------------------------------------------------------------------ #
# def main():
#     if len(sys.argv) < 2:
#         print("""
# Usage:
#   python sfc_converter.py <sfc_file.txt> [output.st]

# Examples:
#   python sfc_converter.py traffic_light.txt
#   python sfc_converter.py traffic_light.txt out/traffic.st

# SFC File Format:
#   steps       = [ { "name": "S1", "function": "F1" }, ... ]
#   transitions = [ { "src": "S1", "tgt": "S2", "guard": "Cond" }, ... ]
#   variables   = [ { "name": "var1", "type": "BOOL" }, ... ]
#   initial_step = "S1"
# """)
#         sys.exit(1)

#     sfc_file = sys.argv[1]
#     out_file = sys.argv[2] if len(sys.argv) > 2 else None

#     if not os.path.exists(sfc_file):
#         print("[ERROR] File not found: {}".format(sfc_file))
#         sys.exit(1)

#     ok = SFCConverter(sfc_file).run(out_file)
#     sys.exit(0 if ok else 1)


# if __name__ == "__main__":
#     main()


#!/usr/bin/env python3
"""
SFC to MATIEC Batch Converter
Processes multiple SFC files, checks MATIEC compilation,
and exports results to console + TXT report.

Usage:
  python sfc_converter_batch.py file1.txt file2.txt ...
  python sfc_converter_batch.py --folder /path/to/sfc_files/
  python sfc_converter_batch.py file1.txt file2.txt --report my_report.txt
"""

import subprocess
import sys
import os
import datetime


class SFCConverter:
    def __init__(self, sfc_file):
        self.sfc_file     = sfc_file
        self.steps        = []
        self.transitions  = []
        self.variables    = []
        self.initial_step = None
        self.st_lines     = []

    # ------------------------------------------------------------------ #
    #  STEP 1  Parse                                                      #
    # ------------------------------------------------------------------ #
    def parse(self):
        print("\n  [STEP 1] Parsing : {}".format(self.sfc_file))
        try:
            with open(self.sfc_file, 'r') as f:
                src = f.read()
            ns = {}
            exec(compile(src, self.sfc_file, 'exec'), {}, ns)
            self.steps        = ns.get('steps',        [])
            self.transitions  = ns.get('transitions',  [])
            self.variables    = ns.get('variables',    [])
            self.initial_step = ns.get('initial_step', None)
            print("         Steps       : {}".format(len(self.steps)))
            print("         Transitions : {}".format(len(self.transitions)))
            print("         Variables   : {}".format(len(self.variables)))
            print("         Initial step: {}".format(self.initial_step))
            return True
        except Exception as e:
            print("         Parse ERROR : {}".format(e))
            return False

    # ------------------------------------------------------------------ #
    #  STEP 2  Generate ST                                               #
    # ------------------------------------------------------------------ #
    def generate(self):
        print("\n  [STEP 2] Generating ST code ...")
        L = self.st_lines
        L.clear()
        L.append("PROGRAM SFC_Program")
        L.append("(* Auto-generated by sfc_converter_batch.py *)")
        L.append("")
        L.append("VAR")
        for s in self.steps:
            L.append("  {}_active : BOOL := FALSE;".format(s['name']))
        for v in self.variables:
            if isinstance(v, dict):
                vname = v.get('name', str(v))
                vtype = v.get('type', 'BOOL')
            else:
                vname, vtype = str(v), 'BOOL'
            init = "0" if vtype in ('INT', 'DINT', 'REAL') else "FALSE"
            L.append("  {} : {} := {};".format(vname, vtype, init))
        L.append("END_VAR")
        L.append("")
        L.append("(* --- Initialise initial step --- *)")
        L.append("IF NOT {}_active THEN".format(self.initial_step))
        L.append("  {}_active := TRUE;".format(self.initial_step))
        L.append("END_IF;")
        L.append("")
        L.append("(* --- Transitions --- *)")
        for t in self.transitions:
            src   = t.get('src',   'UNKNOWN')
            tgt   = t.get('tgt',   'UNKNOWN')
            guard = str(t.get('guard', 'TRUE')).strip() or 'TRUE'
            L.append("IF {}_active AND ({}) THEN".format(src, guard))
            L.append("  {}_active := FALSE;".format(src))
            L.append("  {}_active := TRUE;".format(tgt))
            L.append("END_IF;")
        L.append("")
        L.append("END_PROGRAM")
        print("         {} lines of ST generated.".format(len(L)))

    # ------------------------------------------------------------------ #
    #  STEP 3  Save .st                                                  #
    # ------------------------------------------------------------------ #
    def save(self, out_file):
        print("\n  [STEP 3] Saving : {}".format(out_file))
        try:
            with open(out_file, 'w') as f:
                f.write("\n".join(self.st_lines))
            print("         Saved OK.")
            return True
        except Exception as e:
            print("         Save ERROR : {}".format(e))
            return False

    # ------------------------------------------------------------------ #
    #  STEP 4  Compile with MATIEC (or fallback syntax check)            #
    # ------------------------------------------------------------------ #
    def compile(self, st_file):
        print("\n  [STEP 4] MATIEC compilation ...")
        check = subprocess.run(['which', 'matiec'],
                               capture_output=True, text=True)
        if check.returncode != 0:
            print("         ! MATIEC not found  any built-in syntax check.")
            ok, msg = self._syntax_check(st_file)
            return ok, msg, "Built-in Syntax Check"

        result = subprocess.run(['matiec', '-c', st_file],
                                capture_output=True, text=True, timeout=30)
        if result.returncode == 0:
            return True, "MATIEC compilation successful.", "MATIEC"
        else:
            err = result.stderr.strip() or result.stdout.strip()
            return False, err, "MATIEC"

    # ------------------------------------------------------------------ #
    #  Built-in syntax checker                                           #
    # ------------------------------------------------------------------ #
    def _syntax_check(self, st_file):
        errors = []
        with open(st_file, 'r') as f:
            code = f.read()
        pairs = [
            ('PROGRAM',  'END_PROGRAM'),
            ('VAR',      'END_VAR'),
            ('IF',       'END_IF'),
            ('FOR',      'END_FOR'),
            ('WHILE',    'END_WHILE'),
            ('CASE',     'END_CASE'),
        ]
        for kw_open, kw_close in pairs:
            cnt_open  = len([l for l in code.split('\n')
                             if l.strip().startswith(kw_open)])
            cnt_close = code.count(kw_close)
            if cnt_open != cnt_close:
                errors.append("Mismatched {}/{} ({} open, {} close)"
                              .format(kw_open, kw_close, cnt_open, cnt_close))
        assign_lines = [l.strip() for l in code.split('\n')
                        if ':=' in l and not l.strip().startswith('(*')]
        for line in assign_lines:
            if not line.endswith(';'):
                errors.append("Missing semicolon: {}".format(line))
        if errors:
            return False, "\n".join(errors)
        return True, "Built-in syntax check PASSED."

    # ------------------------------------------------------------------ #
    #  Full pipeline  returns a result dict                             #
    # ------------------------------------------------------------------ #
    def run(self, out_file=None):
        result = {
            "sfc_file"   : self.sfc_file,
            "steps"      : 0,
            "transitions": 0,
            "variables"  : 0,
            "st_file"    : "",
            "compiler"   : "",
            "status"     : "",
            "message"    : "",
            "timestamp"  : datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        }

        parse_ok = self.parse()
        if not parse_ok:
            result.update(status="FAILED", message="Parse error", compiler="N/A")
            return result

        result["steps"]       = len(self.steps)
        result["transitions"] = len(self.transitions)
        result["variables"]   = len(self.variables)

        self.generate()

        if out_file is None:
            base     = os.path.splitext(self.sfc_file)[0]
            out_file = base + ".st"

        result["st_file"] = out_file

        if not self.save(out_file):
            result.update(status="FAILED", message="Save error", compiler="N/A")
            return result

        ok, msg, compiler = self.compile(out_file)
        result["compiler"] = compiler
        result["status"]   = "SUCCESS" if ok else "FAILED"
        result["message"]  = msg

        # Console final banner per file
        print("\n" + "=" * 60)
        print("  FILE     : {}".format(os.path.basename(self.sfc_file)))
        print("  COMPILER : {}".format(compiler))
        print("  RESULT   : --> {}".format(result["status"]))
        if not ok:
            print("  DETAILS  :\n{}".format(msg))
        print("=" * 60)
        return result



#  TXT Report Generator                                                

def generate_txt_report(results, report_path):
    W = 65  # report width
    lines = []

    def rule(char="="):
        return char * W

    def center(text, char=" "):
        return text.center(W)

    def row(label, value):
        return "  {:<22} {}".format(label, value)

  
    lines.append(rule("="))
    lines.append(center("SFC  ->  MATIEC  Compilation Batch Report"))
    lines.append(center("Generated : {}".format(
        datetime.datetime.now().strftime("%Y-%m-%d  %H:%M:%S"))))
    lines.append(rule("="))
    lines.append("")

   
    for idx, r in enumerate(results, start=1):
        lines.append(rule("-"))
        lines.append("  FILE #{} of {}".format(idx, len(results)))
        lines.append(rule("-"))
        lines.append(row("SFC File    :", os.path.basename(r["sfc_file"])))
        lines.append(row("ST File     :", os.path.basename(r.get("st_file", "N/A"))))
        lines.append(row("Steps       :", r["steps"]))
        lines.append(row("Transitions :", r["transitions"]))
        lines.append(row("Variables   :", r["variables"]))
        lines.append(row("Compiler    :", r["compiler"]))
        lines.append(row("Status      :", "[ {} ]".format(r["status"])))
        lines.append(row("Timestamp   :", r["timestamp"]))
        if r["message"]:
            lines.append("")
            lines.append("  Message / Details:")
            for mline in r["message"].splitlines():
                lines.append("    " + mline)
        lines.append("")

   
    total     = len(results)
    successes = sum(1 for r in results if r["status"] == "SUCCESS")
    failures  = total - successes

    lines.append(rule("="))
    lines.append(center("BATCH  SUMMARY"))
    lines.append(rule("="))
    lines.append(row("Total Files :", total))
    lines.append(row("Succeeded   :", successes))
    lines.append(row("Failed      :", failures))
    lines.append("")
    lines.append(rule("-"))
    lines.append("  {:<5} {:<35} {:<15} {}".format(
        "#", "SFC File", "Compiler", "Status"))
    lines.append(rule("-"))
    for idx, r in enumerate(results, start=1):
        icon = "[OK]  " if r["status"] == "SUCCESS" else "[FAIL]"
        name = os.path.basename(r["sfc_file"])[:34]
        lines.append("  {:<5} {:<35} {:<15} {}".format(
            idx, name, r["compiler"], icon))
    lines.append(rule("="))
    lines.append("")

    
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))

    print("\n[REPORT] TXT report saved : {}".format(report_path))



#  Batch runner                                                          #

def run_batch(sfc_files, txt_report="sfc_batch_report.txt"):
    all_results = []
    total = len(sfc_files)

    print("\n" + "" + ""*58 + "")
    print("{:^58}".format("SFC MATIEC Batch Converter"))
    print("{:^58}".format("Total files : {}".format(total)))
    print("" + ""*58 + "")

    for idx, sfc_file in enumerate(sfc_files, start=1):
        print("\n" + ""*60)
        print("  [{}/{}]  {}".format(idx, total, sfc_file))
        print(""*60)

        if not os.path.exists(sfc_file):
            print("  [ERROR] File not found: {}".format(sfc_file))
            all_results.append({
                "sfc_file"   : sfc_file,
                "steps"      : 0,
                "transitions": 0,
                "variables"  : 0,
                "st_file"    : "",
                "compiler"   : "N/A",
                "status"     : "FAILED",
                "message"    : "File not found",
                "timestamp"  : datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            })
            continue

        converter = SFCConverter(sfc_file)
        result    = converter.run()
        all_results.append(result)

    # â”€â”€ Console summary â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ #
    successes = sum(1 for r in all_results if r["status"] == "SUCCESS")
    failures  = len(all_results) - successes

    print("\n" + "" + ""*58 + "")
    print("{:^58}".format("BATCH  SUMMARY"))
    print(" " + " "*58 + "")
    print("  {:<22} {:>32}".format("Total Files :",  total))
    print("  {:<22} {:>32}".format("Succeeded   :",  successes))
    print("  {:<22} {:>32}".format("Failed      :",  failures))
    print(" " + ""*58 + "")
    print("  {:<5} {:<28} {:<14} {:>6}".format(
        "#", "SFC File", "Compiler", "Status"))
    print(" " + " "*58 + " ")
    for r in all_results:
        icon = "[OK]  " if r["status"] == "SUCCESS" else "[FAIL]"
        name = os.path.basename(r["sfc_file"])[:27]
        print("  {:<5} {:<28} {:<14} {:>6}".format(
            all_results.index(r)+1, name, r["compiler"], icon))
    print(" " + " "*58 + " ")

    
    generate_txt_report(all_results, txt_report)
    return all_results



def main():
    if len(sys.argv) < 2:
        print("""
Usage (multiple files):
  python sfc_converter_batch.py file1.txt file2.txt file3.txt

Usage (folder â€“ processes all .txt SFC files inside):
  python sfc_converter_batch.py --folder /path/to/sfc_files/

Optional: specify report output name (default: sfc_batch_report.txt)
  python sfc_converter_batch.py file1.txt file2.txt --report my_report.txt

SFC File Format:
  steps        = [ { "name": "S1", "function": "F1" }, ... ]
  transitions  = [ { "src": "S1", "tgt": "S2", "guard": "Cond" }, ... ]
  variables    = [ { "name": "var1", "type": "BOOL" }, ... ]
  initial_step = "S1"
""")
        sys.exit(1)

    args      = sys.argv[1:]
    txt_name  = "sfc_batch_report.txt"
    sfc_files = []

    # Parse --report flag
    if "--report" in args:
        idx      = args.index("--report")
        txt_name = args[idx + 1]
        args     = [a for i, a in enumerate(args) if i not in (idx, idx+1)]

    # Parse --folder flag
    if "--folder" in args:
        idx    = args.index("--folder")
        folder = args[idx + 1]
        if not os.path.isdir(folder):
            print("[ERROR] Folder not found: {}".format(folder))
            sys.exit(1)
        sfc_files = [
            os.path.join(folder, f)
            for f in sorted(os.listdir(folder))
            if f.endswith(".txt")
        ]
        if not sfc_files:
            print("[ERROR] No .txt SFC files found in: {}".format(folder))
            sys.exit(1)
    else:
        sfc_files = args

    run_batch(sfc_files, txt_name)
    sys.exit(0)


if __name__ == "__main__":
    main()
