
# """
# SFC to MATIEC Batch Converter
# Processes multiple SFC files, checks MATIEC compilation,
# and exports results to console + TXT report.

# Usage:
#   python sfc_converter_batch.py file1.txt file2.txt ...
#   python sfc_converter_batch.py --folder /path/to/sfc_files/
#   python sfc_converter_batch.py file1.txt file2.txt --report my_report.txt
# """

# import re
# import subprocess
# import sys
# import os
# import datetime
# # Add src directory to path for imports
# sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src')) 
# from antarbhukti import codegenutil

# class SFCConverter:
#     def __init__(self, sfc_file):
#         self.sfc_file     = sfc_file
#         self.steps        = []
#         self.transitions  = []
#         self.variables    = []
#         self.initial_step = None
#         self.st_lines     = []

#     # ------------------------------------------------------------------ #
#     #  STEP 1  Parse                                                      #
#     # ------------------------------------------------------------------ #
#     def parse(self):
#         print("\n  [STEP 1] Parsing : {}".format(self.sfc_file))
#         try:
#             with open(self.sfc_file, 'r') as f:
#                 src = f.read()
#             ns = {}
#             exec(compile(src, self.sfc_file, 'exec'), {}, ns)
#             self.steps        = ns.get('steps',        [])
#             self.transitions  = ns.get('transitions',  [])
#             self.variables    = ns.get('variables',    [])
#             self.initial_step = ns.get('initial_step', None)
#             print(
#                 "         Steps       : {}"
#                 "         Transitions : {}"
#                 "         Variables   : {}"
#                 "         Initial step: {}".format(len(self.steps),len(self.transitions),len(self.variables),self.initial_step)
#             )
#             return True
#         except Exception as e:
#             print("         Parse ERROR : {}".format(e))
#             return False

#     def _translate_guard(self, guard):
#         expr = str(guard).strip() if guard is not None else ""
#         if not expr:
#             return "TRUE"

#         # Convert Python-style guard expressions into MATIEC/IEC ST syntax.
#         expr = expr.replace("&&", " AND ").replace("||", " OR ")
#         expr = expr.replace("!=", "<>")
#         expr = expr.replace("==", "=")
#         expr = re.sub(r"\bnot\b", "NOT", expr, flags=re.IGNORECASE)
#         expr = re.sub(r"\band\b", "AND", expr, flags=re.IGNORECASE)
#         expr = re.sub(r"\bor\b", "OR", expr, flags=re.IGNORECASE)
#         expr = re.sub(r"\btrue\b", "TRUE", expr, flags=re.IGNORECASE)
#         expr = re.sub(r"\bfalse\b", "FALSE", expr, flags=re.IGNORECASE)
#         return expr

#     # ------------------------------------------------------------------ #
#     #  STEP 2  Generate ST                                               #
#     # ------------------------------------------------------------------ #
#     def generate(self):
#         print("\n  [STEP 2] Generating ST code ...", end="")
#         L = self.st_lines
#         L.clear()
#         L.append("PROGRAM SFC_Program")
#         L.append("(* Auto-generated by sfc_converter_batch.py *)")
#         L.append("")
#         L.append("VAR")
#         for s in self.steps:
#             L.append("  {}_active : BOOL := FALSE;".format(s['name']))
#         for v in self.variables:
#             if isinstance(v, dict):
#                 vname = v.get('name', str(v))
#                 vtype = v.get('type', 'INT') ## This line is WRONG. Every variable should have a type. ### I make it all integer type variable because in SFC it is not said explicitely 
#             else:
#                 vname, vtype = str(v), 'BOOL'
#             init = "0" if vtype in ('INT', 'DINT', 'REAL') else "FALSE"
#             L.append("  {} : {} := {};".format(vname, vtype, init))
#         L.append("END_VAR")
#         L.append("")
#         L.append("(* --- Initialise initial step --- *)")
#         L.append("IF NOT {}_active THEN".format(self.initial_step))
#         L.append("  {}_active := TRUE;".format(self.initial_step))
#         L.append("END_IF;")
#         L.append("")
#         L.append("(* --- Transitions --- *)")
#         for t in self.transitions:
#             src   = t.get('src',   'UNKNOWN')
#             tgt   = t.get('tgt',   'UNKNOWN')
#             guard = self._translate_guard(t.get('guard', 'TRUE'))
#             L.append("IF {}_active AND ({}) THEN".format(src, guard))
#             L.append("  {}_active := FALSE;".format(src))
#             L.append("  {}_active := TRUE;".format(tgt))
#             L.append("END_IF;")
#         L.append("")
#         L.append("END_PROGRAM")
#         print("         {} lines of ST generated.".format(len(L)))

#     # ------------------------------------------------------------------ #
#     #  STEP 3  Save .st                                                  #
#     # ------------------------------------------------------------------ #
#     def save(self, out_file):
#         print("\n  [STEP 3] Saving : {}".format(out_file))
#         return codegenutil.savefile(out_file, "\n".join(self.st_lines))

#     # ------------------------------------------------------------------ #
#     #  STEP 4  Compile with MATIEC (or fallback syntax check)            #
#     # ------------------------------------------------------------------ #
#     def compile(self, st_file):
#         print("[STEP 4] MATIEC compilation ...{}".format(st_file))
#         result = subprocess.run(["make", "-f", "compile_st.mk", f"SRC={st_file}"], capture_output=True, text=True)
#         if result.returncode == 0:
#             return True, "MATIEC compilation successful.", "MATIEC"
#         else:
#             err = result.stderr.strip() or result.stdout.strip()
#              #ok, msg = self._syntax_check(st_file)
#             return False, err, "MATIEC"

#     # ------------------------------------------------------------------ #
#     #  Built-in syntax checker                                           #
#     # ------------------------------------------------------------------ #
#     def _syntax_check(self, st_file):
#         errors = []
#         with open(st_file, 'r') as f:
#             code = f.read()
#         pairs = [
#             ('PROGRAM',  'END_PROGRAM'),
#             ('VAR',      'END_VAR'),
#             ('IF',       'END_IF'),
#             ('FOR',      'END_FOR'),
#             ('WHILE',    'END_WHILE'),
#             ('CASE',     'END_CASE'),
#         ]
#         for kw_open, kw_close in pairs:
#             cnt_open  = len([l for l in code.split('\n')
#                              if l.strip().startswith(kw_open)])
#             cnt_close = code.count(kw_close)
#             if cnt_open != cnt_close:
#                 errors.append("Mismatched {}/{} ({} open, {} close)"
#                               .format(kw_open, kw_close, cnt_open, cnt_close))
#         assign_lines = [l.strip() for l in code.split('\n')
#                         if ':=' in l and not l.strip().startswith('(*')]
#         for line in assign_lines:
#             if not line.endswith(';'):
#                 errors.append("Missing semicolon: {}".format(line))
#         if errors:
#             return False, "\n".join(errors)
#         return True, "Built-in syntax check PASSED."

#     # ------------------------------------------------------------------ #
#     #  Full pipeline  returns a result dict                             #
#     # ------------------------------------------------------------------ #
#     def run(self, out_file=None):
#         result = {
#             "sfc_file"   : self.sfc_file,
#             "steps"      : 0,
#             "transitions": 0,
#             "variables"  : 0,
#             "st_file"    : "",
#             "compiler"   : "",
#             "status"     : "",
#             "message"    : "",
#             "timestamp"  : datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
#         }

#         parse_ok = self.parse()
#         if not parse_ok:
#             result.update(status="FAILED", message="Parse error", compiler="N/A")
#             return result

#         result["steps"]       = len(self.steps)
#         result["transitions"] = len(self.transitions)
#         result["variables"]   = len(self.variables)

#         self.generate()

#         if out_file is None:
#             out_file     = os.path.splitext(self.sfc_file)[0] + ".st"
#         result["st_file"] = out_file
        
#         if not self.save(out_file):
#             result.update(status="FAILED", message="Save error", compiler="N/A")
#             return result

#         ok, msg, compiler = self.compile(out_file)
#         result["compiler"] = compiler
#         result["status"]   = "SUCCESS" if ok else "FAILED"
#         result["message"]  = msg

#         # Console final banner per file
#         #print("=" * 60)
#         #print("  FILE     : {}".format(os.path.basename(self.sfc_file)))
#         #print("  COMPILER : {}".format(compiler))
#         #print("  RESULT   : --> {}".format(result["status"]))
#         if not ok:
#             print("  DETAILS  :\n{}".format(msg))
#         #print("=" * 60)
#         return result



# #  TXT Report Generator                                                

# def generate_txt_report(results, report_path):
#     W = 65  # report width
#     lines = []

#     def rule(char="="):
#         return char * W

#     def center(text, char=" "):
#         return text.center(W)

#     def row(label, value):
#         return "  {:<22} {}".format(label, value)

  
#     lines.append(rule("="))
#     lines.append(center("SFC  ->  MATIEC  Compilation Batch Report"))
#     lines.append(center("Generated : {}".format(
#         datetime.datetime.now().strftime("%Y-%m-%d  %H:%M:%S"))))
#     lines.append(rule("="))
#     lines.append("")

   
#     for idx, r in enumerate(results, start=1):
#         lines.append(rule("-"))
#         lines.append("  FILE #{} of {}".format(idx, len(results)))
#         lines.append(rule("-"))
#         lines.append(row("SFC File    :", os.path.basename(r["sfc_file"])))
#         lines.append(row("ST File     :", os.path.basename(r.get("st_file", "N/A"))))
#         lines.append(row("Steps       :", r["steps"]))
#         lines.append(row("Transitions :", r["transitions"]))
#         lines.append(row("Variables   :", r["variables"]))
#         lines.append(row("Compiler    :", r["compiler"]))
#         lines.append(row("Status      :", "[ {} ]".format(r["status"])))
#         lines.append(row("Timestamp   :", r["timestamp"]))
#         if r["message"]:
#             lines.append("")
#             lines.append("  Message / Details:")
#             for mline in r["message"].splitlines():
#                 lines.append("    " + mline)
#         lines.append("")

   
#     total     = len(results)
#     successes = sum(1 for r in results if r["status"] == "SUCCESS")
#     failures  = total - successes

#     lines.append(rule("="))
#     lines.append(center("BATCH  SUMMARY"))
#     lines.append(rule("="))
#     lines.append(row("Total Files :", total))
#     lines.append(row("Succeeded   :", successes))
#     lines.append(row("Failed      :", failures))
#     lines.append("")
#     lines.append(rule("-"))
#     lines.append("  {:<5} {:<35} {:<15} {}".format(
#         "#", "SFC File", "Compiler", "Status"))
#     lines.append(rule("-"))
#     for idx, r in enumerate(results, start=1):
#         icon = "[OK]  " if r["status"] == "SUCCESS" else "[FAIL]"
#         name = os.path.basename(r["sfc_file"])[:34]
#         lines.append("  {:<5} {:<35} {:<15} {}".format(
#             idx, name, r["compiler"], icon))
#     lines.append(rule("="))
#     lines.append("")

    
#     with open(report_path, 'w', encoding='utf-8') as f:
#         f.write("\n".join(lines))

#     print("\n[REPORT] TXT report saved : {}".format(report_path))



# #  Batch runner                                                          #

# def run_batch(sfc_files, txt_report="sfc_batch_report.txt"):
#     all_results = []
#     total = len(sfc_files)

#     print("\n" + "" + ""*58 + "")
#     print("{:^58}".format("SFC MATIEC Batch Converter"))
#     print("{:^58}".format("Total files : {}".format(total)))
#     print("" + ""*58 + "")

#     for idx, sfc_file in enumerate(sfc_files, start=1):
#         print("\n" + ""*60)
#         print("  [{}/{}]  {}".format(idx, total, sfc_file))
#         print(""*60)

#         if not os.path.exists(sfc_file):
#             print("  [ERROR] File not found: {}".format(sfc_file))
#             all_results.append({
#                 "sfc_file"   : sfc_file,
#                 "steps"      : 0,
#                 "transitions": 0,
#                 "variables"  : 0,
#                 "st_file"    : "",
#                 "compiler"   : "N/A",
#                 "status"     : "FAILED",
#                 "message"    : "File not found",
#                 "timestamp"  : datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
#             })
#             continue

#         converter = SFCConverter(sfc_file)
#         result    = converter.run()
#         all_results.append(result)

#     # â”€â”€ Console summary â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ #
#     successes = sum(1 for r in all_results if r["status"] == "SUCCESS")
#     failures  = len(all_results) - successes

#     print("\n" + "" + ""*58 + "")
#     print("{:^58}".format("BATCH  SUMMARY"))
#     print(" " + " "*58 + "")
#     print("  {:<22} {:>32}".format("Total Files :",  total))
#     print("  {:<22} {:>32}".format("Succeeded   :",  successes))
#     print("  {:<22} {:>32}".format("Failed      :",  failures))
#     print(" " + ""*58 + "")
#     print("  {:<5} {:<28} {:<14} {:>6}".format(
#         "#", "SFC File", "Compiler", "Status"))
#     print(" " + " "*58 + " ")
#     for r in all_results:
#         icon = "[OK]  " if r["status"] == "SUCCESS" else "[FAIL]"
#         name = os.path.basename(r["sfc_file"])[:27]
#         print("  {:<5} {:<28} {:<14} {:>6}".format(
#             all_results.index(r)+1, name, r["compiler"], icon))
#     print(" " + " "*58 + " ")

    
#     generate_txt_report(all_results, txt_report)
#     return all_results



# def main():
#     if len(sys.argv) < 2:
#         print("""
# Usage (multiple files):
#   python sfc_converter_batch.py file1.txt file2.txt file3.txt

# Usage (folder â€“ processes all .txt SFC files inside):
#   python sfc_converter_batch.py --folder /path/to/sfc_files/

# Optional: specify report output name (default: sfc_batch_report.txt)
#   python sfc_converter_batch.py file1.txt file2.txt --report my_report.txt

# SFC File Format:
#   steps        = [ { "name": "S1", "function": "F1" }, ... ]
#   transitions  = [ { "src": "S1", "tgt": "S2", "guard": "Cond" }, ... ]
#   variables    = [ { "name": "var1", "type": "BOOL" }, ... ]
#   initial_step = "S1"
# """)
#         sys.exit(1)

#     args      = sys.argv[1:]
#     txt_name  = "sfc_batch_report.txt"
#     sfc_files = []

#     # Parse --report flag
#     if "--report" in args:
#         idx      = args.index("--report")
#         txt_name = args[idx + 1]
#         args     = [a for i, a in enumerate(args) if i not in (idx, idx+1)]

#     # Parse --folder flag
#     if "--folder" in args:
#         idx    = args.index("--folder")
#         folder = args[idx + 1]
#         if not os.path.isdir(folder):
#             print("[ERROR] Folder not found: {}".format(folder))
#             sys.exit(1)
#         sfc_files = codegenutil.readfiles(folder)  # Just to check if folder is readable
#         #sfc_files = [ os.path.join(folder, f) for f in sorted(os.listdir(folder)) if f.endswith(".txt")]
#         if not sfc_files:
#             print("[ERROR] No .txt SFC files found in: {}".format(folder))
#             sys.exit(1)
#     else:
#         sfc_files = args

#     run_batch(sfc_files, txt_name)
#     sys.exit(0)


# # ======================================================================== #
# # JSON-based SFC Converter - processes sfc_baseline and sfc_upgraded       #
# # ======================================================================== #

# class SFCJSONConverter:
#     """
#     Converts SFC definitions from JSON format (containing sfc_baseline and 
#     sfc_upgraded) into two ST files for separate compilation.
#     """
    
#     def __init__(self, json_file):
#         self.json_file = json_file
#         self.baseline_sfc = None
#         self.upgraded_sfc = None
#         self.baseline_st_lines = []
#         self.upgraded_st_lines = []
    
#     def parse(self):
#         """Parse JSON file and extract baseline and upgraded SFC definitions."""
#         import json
#         print("\n  [STEP 1] Parsing JSON file: {}".format(self.json_file))
#         try:
#             with open(self.json_file, 'r') as f:
#                 data = json.load(f)
            
#             self.baseline_sfc = data.get('sfc_baseline', {})
#             self.upgraded_sfc = data.get('sfc_upgraded', {})
            
#             print("    Baseline SFC:")
#             print("      Steps       : {}".format(len(self.baseline_sfc.get('steps', []))))
#             print("      Transitions : {}".format(len(self.baseline_sfc.get('transitions', []))))
#             print("      Variables   : {}".format(len(self.baseline_sfc.get('variables', []))))
            
#             print("    Upgraded SFC:")
#             print("      Steps       : {}".format(len(self.upgraded_sfc.get('steps', []))))
#             print("      Transitions : {}".format(len(self.upgraded_sfc.get('transitions', []))))
#             print("      Variables   : {}".format(len(self.upgraded_sfc.get('variables', []))))
            
#             return True
#         except Exception as e:
#             print("    Parse ERROR: {}".format(e))
#             return False
    
#     def _translate_guard(self, guard):
#         """Translate guard expressions from Python-style to MATIEC/IEC ST syntax."""
#         expr = str(guard).strip() if guard is not None else ""
#         if not expr:
#             return "TRUE"
        
#         expr = expr.replace("&&", " AND ").replace("||", " OR ")
#         expr = expr.replace("!=", "<>")
#         expr = expr.replace("==", "=")
#         expr = re.sub(r"\bnot\b", "NOT", expr, flags=re.IGNORECASE)
#         expr = re.sub(r"\band\b", "AND", expr, flags=re.IGNORECASE)
#         expr = re.sub(r"\bor\b", "OR", expr, flags=re.IGNORECASE)
#         expr = re.sub(r"\btrue\b", "TRUE", expr, flags=re.IGNORECASE)
#         expr = re.sub(r"\bfalse\b", "FALSE", expr, flags=re.IGNORECASE)
#         return expr
    
#     def _generate_st(self, sfc_data, output_lines):
#         """
#         Generate ST code from SFC data (baseline or upgraded).
#         Appends to output_lines list.
#         """
#         L = output_lines
#         steps = sfc_data.get('steps', [])
#         transitions = sfc_data.get('transitions', [])
#         variables = sfc_data.get('variables', [])
#         initial_step = sfc_data.get('initial_step', None)
        
#         L.append("PROGRAM SFC_Program")
#         L.append("(* Auto-generated by SFCJSONConverter *)")
#         L.append("")
#         L.append("VAR")
        
#         # Step flags
#         for s in steps:
#             step_name = s.get('name', 'UNKNOWN') if isinstance(s, dict) else str(s)
#             L.append("  {}_active : BOOL := FALSE;".format(step_name))
        
#         # User variables
#         for v in variables:
#             if isinstance(v, dict):
#                 vname = v.get('name', str(v))
#                 vtype = v.get('type', 'BOOL')
#             else:
#                 vname, vtype = str(v), 'BOOL'
#             init = "0" if vtype in ('INT', 'DINT', 'REAL') else "FALSE"
#             L.append("  {} : {} := {};".format(vname, vtype, init))
        
#         L.append("END_VAR")
#         L.append("")
        
#         # Initialize initial step
#         L.append("(* --- Initialize initial step --- *)")
#         L.append("IF NOT {}_active THEN".format(initial_step))
#         L.append("  {}_active := TRUE;".format(initial_step))
#         L.append("END_IF;")
#         L.append("")
        
#         # Step actions
#         L.append("(* --- Step actions --- *)")
#         for s in steps:
#             if isinstance(s, dict):
#                 step_name = s.get('name', 'UNKNOWN')
#                 step_func = s.get('function', '').strip()
#             else:
#                 step_name = str(s)
#                 step_func = ''
            
#             if step_func:
#                 L.append("IF {}_active THEN".format(step_name))
#                 L.append("  {};".format(step_func))
#                 L.append("END_IF;")
        
#         L.append("")
        
#         # Transitions
#         L.append("(* --- Transitions --- *)")
#         for t in transitions:
#             src = t.get('src', 'UNKNOWN')
#             tgt = t.get('tgt', 'UNKNOWN')
#             guard = self._translate_guard(t.get('guard', 'TRUE'))
            
#             L.append("IF {}_active AND ({}) THEN".format(src, guard))
#             L.append("  {}_active := FALSE;".format(src))
#             L.append("  {}_active := TRUE;".format(tgt))
#             L.append("END_IF;")
        
#         L.append("")
#         L.append("END_PROGRAM")
    
#     def generate(self):
#         """
#         Generate ST code for both baseline and upgraded SFC definitions.
#         """
#         print("\n  [STEP 2] Generating ST code for both baseline and upgraded ...")
        
#         self.baseline_st_lines.clear()
#         self.upgraded_st_lines.clear()
        
#         self._generate_st(self.baseline_sfc, self.baseline_st_lines)
#         self._generate_st(self.upgraded_sfc, self.upgraded_st_lines)
        
#         print("    Baseline ST : {} lines generated.".format(len(self.baseline_st_lines)))
#         print("    Upgraded ST : {} lines generated.".format(len(self.upgraded_st_lines)))
    
#     def save(self, baseline_out, upgraded_out):
#         """
#         Save both baseline and upgraded ST files.
#         """
#         print("\n  [STEP 3] Saving : {}...  ".format(baseline_out), end="")
#         baseline_ok = codegenutil.savefile(baseline_out, "\n".join(self.baseline_st_lines))
        
#         print("\n  [STEP 3] Saving : {}".format(upgraded_out))
#         upgraded_ok = codegenutil.savefile(upgraded_out, "\n".join(self.upgraded_st_lines))
        
#         return baseline_ok and upgraded_ok
    
#     def compile(self, baseline_st_file, upgraded_st_file):
#         """
#         Compile both ST files using iec2iec (or MATIEC).
#         Returns (baseline_ok, baseline_msg, upgraded_ok, upgraded_msg)
#         """
#         print("\n  [STEP 4] Compiling both ST files with iec2iec ...")
        
#         def compile_file(st_file, label):
#             """Compile a single ST file."""
#             print("\n    Compiling {} : {}".format(label, st_file))
#             result = subprocess.run(
#                 ["make", "-f", "compile_st.mk", "SRC={}".format(st_file)],
#                 capture_output=True,
#                 text=True,
#                 timeout=30
#             )
            
#             if result.returncode == 0:
#                 return True, "Compilation successful."
#             else:
#                 err = result.stderr.strip() or result.stdout.strip()
#                 return False, err
        
#         baseline_ok, baseline_msg = compile_file(baseline_st_file, "BASELINE")
#         upgraded_ok, upgraded_msg = compile_file(upgraded_st_file, "UPGRADED")
        
#         return baseline_ok, baseline_msg, upgraded_ok, upgraded_msg
    
#     def run(self, baseline_out=None, upgraded_out=None):
#         """
#         Full pipeline: parse JSON, generate ST files, save them, and compile.
#         Returns a result dictionary for batch processing.
#         """
#         result = {
#             "json_file"   : self.json_file,
#             "baseline_steps"      : 0,
#             "baseline_transitions": 0,
#             "baseline_variables"  : 0,
#             "upgraded_steps"      : 0,
#             "upgraded_transitions": 0,
#             "upgraded_variables"  : 0,
#             "baseline_st_file"    : "",
#             "upgraded_st_file"    : "",
#             "status"     : "",
#             "message"    : "",
#             "timestamp"  : datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
#         }
        
#         parse_ok = self.parse()
#         if not parse_ok:
#             result.update(status="FAILED", message="Parse error")
#             return result
        
#         result["baseline_steps"]       = len(self.baseline_sfc.get('steps', []))
#         result["baseline_transitions"] = len(self.baseline_sfc.get('transitions', []))
#         result["baseline_variables"]   = len(self.baseline_sfc.get('variables', []))
#         result["upgraded_steps"]       = len(self.upgraded_sfc.get('steps', []))
#         result["upgraded_transitions"] = len(self.upgraded_sfc.get('transitions', []))
#         result["upgraded_variables"]   = len(self.upgraded_sfc.get('variables', []))
        
#         self.generate()
        
#         if baseline_out is None:
#             base = os.path.splitext(self.json_file)[0]
#             baseline_out = base + "_baseline.st"
#             upgraded_out = base + "_upgraded.st"
        
#         result["baseline_st_file"] = baseline_out
#         result["upgraded_st_file"] = upgraded_out
        
#         if not self.save(baseline_out, upgraded_out):
#             result.update(status="FAILED", message="Save error")
#             return result
        
#         b_ok, b_msg, u_ok, u_msg = self.compile(baseline_out, upgraded_out)
        
#         result["status"] = "SUCCESS" if (b_ok and u_ok) else "FAILED"
#         result["message"] = "Baseline: {}\nUpgraded: {}".format(
#             "OK" if b_ok else "FAILED - {}".format(b_msg),
#             "OK" if u_ok else "FAILED - {}".format(u_msg)
#         )
        
#         # Console final banner per file
#         if not (b_ok and u_ok):
#             print("  DETAILS  :\n{}".format(result["message"]))
        
#         return result


# #  Batch runner for JSON files                                          #

# def run_batch_json(json_files, txt_report="json_batch_report.txt"):
#     all_results = []
#     total = len(json_files)

#     print("\n" + "" + ""*58 + "")
#     print("{:^58}".format("JSON SFC MATIEC Batch Converter"))
#     print("{:^58}".format("Total files : {}".format(total)))
#     print("" + ""*58 + "")

#     for idx, json_file in enumerate(json_files, start=1):
#         print("\n" + ""*60)
#         print("  [{}/{}]  {}".format(idx, total, json_file))
#         print(""*60)

#         if not os.path.exists(json_file):
#             print("  [ERROR] File not found: {}".format(json_file))
#             all_results.append({
#                 "json_file"   : json_file,
#                 "baseline_steps"      : 0,
#                 "baseline_transitions": 0,
#                 "baseline_variables"  : 0,
#                 "upgraded_steps"      : 0,
#                 "upgraded_transitions": 0,
#                 "upgraded_variables"  : 0,
#                 "baseline_st_file"    : "",
#                 "upgraded_st_file"    : "",
#                 "status"     : "FAILED",
#                 "message"    : "File not found",
#                 "timestamp"  : datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
#             })
#             continue

#         converter = SFCJSONConverter(json_file)
#         result    = converter.run()
#         all_results.append(result)

#     # â"€â"€ Console summary â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€ #
#     successes = sum(1 for r in all_results if r["status"] == "SUCCESS")
#     failures  = len(all_results) - successes

#     print("\n" + "" + ""*58 + "")
#     print("{:^58}".format("BATCH  SUMMARY"))
#     print(" " + " "*58 + "")
#     print("  {:<22} {:>32}".format("Total Files :",  total))
#     print("  {:<22} {:>32}".format("Succeeded   :",  successes))
#     print("  {:<22} {:>32}".format("Failed      :",  failures))
#     print(" " + ""*58 + "")
#     print("  {:<5} {:<28} {:>6}".format(
#         "#", "JSON File", "Status"))
#     print(" " + " "*58 + " ")
#     for r in all_results:
#         icon = "[OK]  " if r["status"] == "SUCCESS" else "[FAIL]"
#         name = os.path.basename(r["json_file"])[:27]
#         print("  {:<5} {:<28} {:>6}".format(
#             all_results.index(r)+1, name, icon))
#     print(" " + " "*58 + " ")

#     return all_results


# def main_json():
#     """Entry point for JSON-based batch conversion."""
#     if len(sys.argv) < 2:
#         print("""
# Usage (multiple files):
#   python sfc_converter.py file1.json file2.json file3.json

# Usage (folder â€" processes all .json SFC files inside):
#   python sfc_converter.py --folder /path/to/json_files/

# Optional: specify report output name (default: json_batch_report.txt)
#   python sfc_converter.py file1.json file2.json --report my_report.txt

# JSON File Format:
#   {{
#     "id": "...",
#     "sfc_baseline": {{
#       "steps": [...],
#       "transitions": [...],
#       "variables": [...],
#       "initial_step": "..."
#     }},
#     "sfc_upgraded": {{
#       "steps": [...],
#       "transitions": [...],
#       "variables": [...],
#       "initial_step": "..."
#     }}
#   }}
# """)
#         sys.exit(1)

#     args      = sys.argv[1:]
#     txt_name  = "json_batch_report.txt"
#     json_files = []

#     # Parse --report flag
#     if "--report" in args:
#         idx      = args.index("--report")
#         txt_name = args[idx + 1]
#         args     = [a for i, a in enumerate(args) if i not in (idx, idx+1)]

#     # Parse --folder flag
#     if "--folder" in args:
#         idx    = args.index("--folder")
#         folder = args[idx + 1]
#         if not os.path.isdir(folder):
#             print("[ERROR] Folder not found: {}".format(folder))
#             sys.exit(1)
#         json_files = codegenutil.readfiles(folder)  # Recursively reads files from folder
#         if not json_files:
#             print("[ERROR] No .json SFC files found in: {}".format(folder))
#             sys.exit(1)
#     else:
#         json_files = args

#     run_batch_json(json_files, txt_name)
#     sys.exit(0)


# if __name__ == "__main__":
#     main()

"""
SFC to MATIEC Batch Converter
Processes multiple SFC files, checks MATIEC compilation,
and exports results to console + TXT report.

Usage:
  python sfc_converter_batch.py file1.txt file2.txt ...
  python sfc_converter_batch.py --folder /path/to/sfc_files/
  python sfc_converter_batch.py file1.txt file2.txt --report my_report.txt
"""

import re
import subprocess
import sys
import os
import datetime
# Add src directory to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src')) 
from antarbhukti import codegenutil

class SFCConverter:
    def __init__(self, sfc_file):
        self.sfc_file     = sfc_file
        self.steps        = []
        self.transitions  = []
        self.variables    = []
        self.initial_step = None
        self.st_lines     = []

    # ------------------------------------------------------------------ #
    #  STEP 1  Parse                                                      #
    # ------------------------------------------------------------------ #
    def parse(self):
        print("\n  [STEP 1] Parsing : {}".format(self.sfc_file))
        try:
            with open(self.sfc_file, 'r') as f:
                src = f.read()
            ns = {}
            exec(compile(src, self.sfc_file, 'exec'), {}, ns)
            self.steps        = ns.get('steps',        [])
            self.transitions  = ns.get('transitions',  [])
            self.variables    = ns.get('variables',    [])
            self.initial_step = ns.get('initial_step', None)
            print(
                "         Steps       : {}"
                "         Transitions : {}"
                "         Variables   : {}"
                "         Initial step: {}".format(len(self.steps),len(self.transitions),len(self.variables),self.initial_step)
            )
            return True
        except Exception as e:
            print("         Parse ERROR : {}".format(e))
            return False

    def _infer_variable_type(self, variable_dict, var_name=""):
        """
        Infer variable type based on initialization value or variable name patterns.
        If variable has explicit 'type', use it.
        Otherwise, check 'init' value:
        - If TRUE/FALSE -> BOOL
        - If number -> INT or REAL
        - If variable name suggests BOOL (Q, enabled, etc.) -> BOOL
        - Otherwise -> INT (default for numeric variables)
        """
        if isinstance(variable_dict, dict):
            # Explicit type provided
            if 'type' in variable_dict and variable_dict['type']:
                return variable_dict['type']
            
            # Try to infer from init value
            if 'init' in variable_dict:
                init_val = variable_dict['init']
                # Check if it's a boolean
                if isinstance(init_val, bool):
                    return 'BOOL'
                # Check if it's a string representation of TRUE/FALSE
                if isinstance(init_val, str) and init_val.upper() in ('TRUE', 'FALSE'):
                    return 'BOOL'
                # Check if it's a float
                if isinstance(init_val, float):
                    return 'REAL'
                # Check if it's an integer (but not boolean, since bool is subclass of int)
                if isinstance(init_val, int) and not isinstance(init_val, bool):
                    return 'INT'
                # Try to parse as number
                try:
                    if '.' in str(init_val):
                        float(init_val)
                        return 'REAL'
                    else:
                        int(init_val)
                        return 'INT'
                except (ValueError, TypeError):
                    pass
            
            # Try to infer from 'value' field (alternative naming)
            if 'value' in variable_dict:
                val = variable_dict['value']
                if isinstance(val, bool):
                    return 'BOOL'
                if isinstance(val, str) and val.upper() in ('TRUE', 'FALSE'):
                    return 'BOOL'
                if isinstance(val, float):
                    return 'REAL'
                if isinstance(val, int) and not isinstance(val, bool):
                    return 'INT'
                try:
                    if '.' in str(val):
                        float(val)
                        return 'REAL'
                    else:
                        int(val)
                        return 'INT'
                except (ValueError, TypeError):
                    pass
        
        # If it's a plain string variable, check naming patterns
        if var_name:
            var_name_lower = var_name.lower()
            # Common BOOL variable patterns
            if any(pattern in var_name_lower for pattern in ['q', 'enabled', 'active', 'flag', 'is_', 'has_', 'error', 'status']):
                return 'BOOL'
            # Common REAL variable patterns
            if any(pattern in var_name_lower for pattern in ['temperature', 'pressure', 'voltage', 'current', 'flow', 'speed', 'position', 'time', 'distance', 'weight', 'value', 'margin', 'log_']):
                return 'REAL'
        
        # Default to INT for numeric variables
        return 'INT'

    def _get_variable_init_value(self, variable_dict, var_type):
        """
        Get the initial value for a variable based on its type.
        """
        if isinstance(variable_dict, dict):
            # Explicit init value provided
            if 'init' in variable_dict:
                init_val = variable_dict['init']
                if var_type == 'BOOL':
                    if isinstance(init_val, bool):
                        return 'TRUE' if init_val else 'FALSE'
                    elif isinstance(init_val, str) and init_val.upper() in ('TRUE', 'FALSE'):
                        return init_val.upper()
                    else:
                        return 'FALSE'
                else:
                    return str(init_val)
            
            if 'value' in variable_dict:
                val = variable_dict['value']
                if var_type == 'BOOL':
                    if isinstance(val, bool):
                        return 'TRUE' if val else 'FALSE'
                    elif isinstance(val, str) and val.upper() in ('TRUE', 'FALSE'):
                        return val.upper()
                    else:
                        return 'FALSE'
                else:
                    return str(val)
        
        # Default init values based on type
        if var_type == 'BOOL':
            return 'FALSE'
        elif var_type in ('INT', 'DINT'):
            return '0'
        elif var_type == 'REAL':
            return '0.0'
        else:
            return '0'

    def _translate_guard(self, guard):
        expr = str(guard).strip() if guard is not None else ""
        if not expr:
            return "TRUE"

        # Convert Python-style guard expressions into MATIEC/IEC ST syntax.
        expr = expr.replace("&&", " AND ").replace("||", " OR ")
        expr = expr.replace("!=", "<>")
        expr = expr.replace("==", "=")
        expr = re.sub(r"\bnot\b", "NOT", expr, flags=re.IGNORECASE)
        expr = re.sub(r"\band\b", "AND", expr, flags=re.IGNORECASE)
        expr = re.sub(r"\bor\b", "OR", expr, flags=re.IGNORECASE)
        expr = re.sub(r"\btrue\b", "TRUE", expr, flags=re.IGNORECASE)
        expr = re.sub(r"\bfalse\b", "FALSE", expr, flags=re.IGNORECASE)
        return expr

    # ------------------------------------------------------------------ #
    #  STEP 2  Generate ST                                               #
    # ------------------------------------------------------------------ #
    def generate(self):
        print("\n  [STEP 2] Generating ST code ...", end="")
        L = self.st_lines
        L.clear()
        L.append("PROGRAM SFC_Program")
        L.append("(* Auto-generated by sfc_converter_batch.py *)")
        L.append("")
        L.append("VAR")
        for s in self.steps:
            L.append("  {}_active : BOOL := FALSE;".format(s['name']))
        
        for v in self.variables:
            if isinstance(v, dict):
                vname = v.get('name', str(v))
                # Infer type based on init value or name
                vtype = self._infer_variable_type(v, vname)
            else:
                vname = str(v)
                # For plain strings, infer type from variable name
                vtype = self._infer_variable_type(None, vname)
            
            # Get proper initial value for the inferred type
            init = self._get_variable_init_value(v, vtype)
            L.append("  {} : {} := {};".format(vname, vtype, init))
        
        L.append("END_VAR")
        L.append("")
        L.append("(* --- Initialise initial step --- *)")
        L.append("IF NOT {}_active THEN".format(self.initial_step))
        L.append("  {}_active := TRUE;".format(self.initial_step))
        L.append("END_IF;")
        L.append("")
        L.append("(* --- Transitions --- *)")
        for t in self.transitions:
            src   = t.get('src',   'UNKNOWN')
            tgt   = t.get('tgt',   'UNKNOWN')
            guard = self._translate_guard(t.get('guard', 'TRUE'))
            L.append("IF {}_active AND ({}) THEN".format(src, guard))
            L.append("  {}_active := FALSE;".format(src))
            L.append("  {}_active := TRUE;".format(tgt))
            L.append("END_IF;")
        L.append("")
        L.append("END_PROGRAM")
        print("         {} lines of ST generated.".format(len(L)))

    # ------------------------------------------------------------------ #
    #  STEP 3  Save .st                                                  #
    # ------------------------------------------------------------------ #
    def save(self, out_file):
        print("\n  [STEP 3] Saving : {}".format(out_file))
        return codegenutil.savefile(out_file, "\n".join(self.st_lines))

    # ------------------------------------------------------------------ #
    #  STEP 4  Compile with MATIEC (or fallback syntax check)            #
    # ------------------------------------------------------------------ #
    def compile(self, st_file):
        print("[STEP 4] MATIEC compilation ...{}".format(st_file))
        result = subprocess.run(["make", "-f", "compile_st.mk", f"SRC={st_file}"], capture_output=True, text=True)
        if result.returncode == 0:
            return True, "MATIEC compilation successful.", "MATIEC"
        else:
            err = result.stderr.strip() or result.stdout.strip()
             #ok, msg = self._syntax_check(st_file)
            return False, err, "MATIEC"

    # ------------------------------------------------------------------ #
    #  Built-in syntax checker                                           #
    # ------------------------------------------------------------------ #
    def _syntax_check(self, st_file):
        errors = []
        with open(st_file, 'r') as f:
            code = f.read()
        pairs = [
            ('PROGRAM',  'END_PROGRAM'),
            ('VAR',      'END_VAR'),
            ('IF',       'END_IF'),
            ('FOR',      'END_FOR'),
            ('WHILE',    'END_WHILE'),
            ('CASE',     'END_CASE'),
        ]
        for kw_open, kw_close in pairs:
            cnt_open  = len([l for l in code.split('\n')
                             if l.strip().startswith(kw_open)])
            cnt_close = code.count(kw_close)
            if cnt_open != cnt_close:
                errors.append("Mismatched {}/{} ({} open, {} close)"
                              .format(kw_open, kw_close, cnt_open, cnt_close))
        assign_lines = [l.strip() for l in code.split('\n')
                        if ':=' in l and not l.strip().startswith('(*')]
        for line in assign_lines:
            if not line.endswith(';'):
                errors.append("Missing semicolon: {}".format(line))
        if errors:
            return False, "\n".join(errors)
        return True, "Built-in syntax check PASSED."

    # ------------------------------------------------------------------ #
    #  Full pipeline  returns a result dict                             #
    # ------------------------------------------------------------------ #
    def run(self, out_file=None):
        result = {
            "sfc_file"   : self.sfc_file,
            "steps"      : 0,
            "transitions": 0,
            "variables"  : 0,
            "st_file"    : "",
            "compiler"   : "",
            "status"     : "",
            "message"    : "",
            "timestamp"  : datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        }

        parse_ok = self.parse()
        if not parse_ok:
            result.update(status="FAILED", message="Parse error", compiler="N/A")
            return result

        result["steps"]       = len(self.steps)
        result["transitions"] = len(self.transitions)
        result["variables"]   = len(self.variables)

        self.generate()

        if out_file is None:
            out_file     = os.path.splitext(self.sfc_file)[0] + ".st"
        result["st_file"] = out_file
        
        if not self.save(out_file):
            result.update(status="FAILED", message="Save error", compiler="N/A")
            return result

        ok, msg, compiler = self.compile(out_file)
        result["compiler"] = compiler
        result["status"]   = "SUCCESS" if ok else "FAILED"
        result["message"]  = msg

        # Console final banner per file
        #print("=" * 60)
        #print("  FILE     : {}".format(os.path.basename(self.sfc_file)))
        #print("  COMPILER : {}".format(compiler))
        #print("  RESULT   : --> {}".format(result["status"]))
        if not ok:
            print("  DETAILS  :\n{}".format(msg))
        #print("=" * 60)
        return result



#  TXT Report Generator                                                

def generate_txt_report(results, report_path):
    W = 65  # report width
    lines = []

    def rule(char="="):
        return char * W

    def center(text, char=" "):
        return text.center(W)

    def row(label, value):
        return "  {:<22} {}".format(label, value)

  
    lines.append(rule("="))
    lines.append(center("SFC  ->  MATIEC  Compilation Batch Report"))
    lines.append(center("Generated : {}".format(
        datetime.datetime.now().strftime("%Y-%m-%d  %H:%M:%S"))))
    lines.append(rule("="))
    lines.append("")

   
    for idx, r in enumerate(results, start=1):
        lines.append(rule("-"))
        lines.append("  FILE #{} of {}".format(idx, len(results)))
        lines.append(rule("-"))
        lines.append(row("SFC File    :", os.path.basename(r["sfc_file"])))
        lines.append(row("ST File     :", os.path.basename(r.get("st_file", "N/A"))))
        lines.append(row("Steps       :", r["steps"]))
        lines.append(row("Transitions :", r["transitions"]))
        lines.append(row("Variables   :", r["variables"]))
        lines.append(row("Compiler    :", r["compiler"]))
        lines.append(row("Status      :", "[ {} ]".format(r["status"])))
        lines.append(row("Timestamp   :", r["timestamp"]))
        if r["message"]:
            lines.append("")
            lines.append("  Message / Details:")
            for mline in r["message"].splitlines():
                lines.append("    " + mline)
        lines.append("")

   
    total     = len(results)
    successes = sum(1 for r in results if r["status"] == "SUCCESS")
    failures  = total - successes

    lines.append(rule("="))
    lines.append(center("BATCH  SUMMARY"))
    lines.append(rule("="))
    lines.append(row("Total Files :", total))
    lines.append(row("Succeeded   :", successes))
    lines.append(row("Failed      :", failures))
    lines.append("")
    lines.append(rule("-"))
    lines.append("  {:<5} {:<35} {:<15} {}".format(
        "#", "SFC File", "Compiler", "Status"))
    lines.append(rule("-"))
    for idx, r in enumerate(results, start=1):
        icon = "[OK]  " if r["status"] == "SUCCESS" else "[FAIL]"
        name = os.path.basename(r["sfc_file"])[:34]
        lines.append("  {:<5} {:<35} {:<15} {}".format(
            idx, name, r["compiler"], icon))
    lines.append(rule("="))
    lines.append("")

    
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))

    print("\n[REPORT] TXT report saved : {}".format(report_path))



#  Batch runner                                                          #

def run_batch(sfc_files, txt_report="sfc_batch_report.txt"):
    all_results = []
    total = len(sfc_files)

    print("\n" + "" + ""*58 + "")
    print("{:^58}".format("SFC MATIEC Batch Converter"))
    print("{:^58}".format("Total files : {}".format(total)))
    print("" + ""*58 + "")

    for idx, sfc_file in enumerate(sfc_files, start=1):
        print("\n" + ""*60)
        print("  [{}/{}]  {}".format(idx, total, sfc_file))
        print(""*60)

        if not os.path.exists(sfc_file):
            print("  [ERROR] File not found: {}".format(sfc_file))
            all_results.append({
                "sfc_file"   : sfc_file,
                "steps"      : 0,
                "transitions": 0,
                "variables"  : 0,
                "st_file"    : "",
                "compiler"   : "N/A",
                "status"     : "FAILED",
                "message"    : "File not found",
                "timestamp"  : datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            })
            continue

        converter = SFCConverter(sfc_file)
        result    = converter.run()
        all_results.append(result)

    # â"€â"€ Console summary â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€ #
    successes = sum(1 for r in all_results if r["status"] == "SUCCESS")
    failures  = len(all_results) - successes

    print("\n" + "" + ""*58 + "")
    print("{:^58}".format("BATCH  SUMMARY"))
    print(" " + " "*58 + "")
    print("  {:<22} {:>32}".format("Total Files :",  total))
    print("  {:<22} {:>32}".format("Succeeded   :",  successes))
    print("  {:<22} {:>32}".format("Failed      :",  failures))
    print(" " + ""*58 + "")
    print("  {:<5} {:<28} {:<14} {:>6}".format(
        "#", "SFC File", "Compiler", "Status"))
    print(" " + " "*58 + " ")
    for r in all_results:
        icon = "[OK]  " if r["status"] == "SUCCESS" else "[FAIL]"
        name = os.path.basename(r["sfc_file"])[:27]
        print("  {:<5} {:<28} {:<14} {:>6}".format(
            all_results.index(r)+1, name, r["compiler"], icon))
    print(" " + " "*58 + " ")

    
    generate_txt_report(all_results, txt_report)
    return all_results



def main():
    if len(sys.argv) < 2:
        print("""
Usage (multiple files):
  python sfc_converter_batch.py file1.txt file2.txt file3.txt

Usage (folder – processes all .txt SFC files inside):
  python sfc_converter_batch.py --folder /path/to/sfc_files/

Optional: specify report output name (default: sfc_batch_report.txt)
  python sfc_converter_batch.py file1.txt file2.txt --report my_report.txt

SFC File Format:
  steps        = [ { "name": "S1", "function": "F1" }, ... ]
  transitions  = [ { "src": "S1", "tgt": "S2", "guard": "Cond" }, ... ]
  variables    = [ "IN", "OUT" ]  OR  [ { "name": "var1", "type": "BOOL", "init": True }, ... ]
  initial_step = "S1"
""")
        sys.exit(1)

    args      = sys.argv[1:]
    txt_name  = "sfc_batch_report.txt"
    sfc_files = []

    # Parse --report flag
    if "--report" in args:
        idx      = args.index("--report")
        txt_name = args[idx + 1]
        args     = [a for i, a in enumerate(args) if i not in (idx, idx+1)]

    # Parse --folder flag
    if "--folder" in args:
        idx    = args.index("--folder")
        folder = args[idx + 1]
        if not os.path.isdir(folder):
            print("[ERROR] Folder not found: {}".format(folder))
            sys.exit(1)
        sfc_files = codegenutil.readfiles(folder)  # Just to check if folder is readable
        #sfc_files = [ os.path.join(folder, f) for f in sorted(os.listdir(folder)) if f.endswith(".txt")]
        if not sfc_files:
            print("[ERROR] No .txt SFC files found in: {}".format(folder))
            sys.exit(1)
    else:
        sfc_files = args

    run_batch(sfc_files, txt_name)
    sys.exit(0)


# ======================================================================== #
# JSON-based SFC Converter - processes sfc_baseline and sfc_upgraded       #
# ======================================================================== #

class SFCJSONConverter:
    """
    Converts SFC definitions from JSON format (containing sfc_baseline and 
    sfc_upgraded) into two ST files for separate compilation.
    """
    
    def __init__(self, json_file):
        self.json_file = json_file
        self.baseline_sfc = None
        self.upgraded_sfc = None
        self.baseline_st_lines = []
        self.upgraded_st_lines = []
    
    def parse(self):
        """Parse JSON file and extract baseline and upgraded SFC definitions."""
        import json
        print("\n  [STEP 1] Parsing JSON file: {}".format(self.json_file))
        try:
            with open(self.json_file, 'r') as f:
                data = json.load(f)
            
            self.baseline_sfc = data.get('sfc_baseline', {})
            self.upgraded_sfc = data.get('sfc_upgraded', {})
            
            print("    Baseline SFC:")
            print("      Steps       : {}".format(len(self.baseline_sfc.get('steps', []))))
            print("      Transitions : {}".format(len(self.baseline_sfc.get('transitions', []))))
            print("      Variables   : {}".format(len(self.baseline_sfc.get('variables', []))))
            
            print("    Upgraded SFC:")
            print("      Steps       : {}".format(len(self.upgraded_sfc.get('steps', []))))
            print("      Transitions : {}".format(len(self.upgraded_sfc.get('transitions', []))))
            print("      Variables   : {}".format(len(self.upgraded_sfc.get('variables', []))))
            
            return True
        except Exception as e:
            print("    Parse ERROR: {}".format(e))
            return False
    
    def _infer_variable_type(self, variable_dict, var_name=""):
        """
        Infer variable type based on initialization value or variable name patterns.
        If variable has explicit 'type', use it.
        Otherwise, check 'init' value:
        - If TRUE/FALSE -> BOOL
        - If number -> INT or REAL
        - If variable name suggests BOOL (Q, enabled, etc.) -> BOOL
        - Otherwise -> INT (default for numeric variables)
        """
        if isinstance(variable_dict, dict):
            # Explicit type provided
            if 'type' in variable_dict and variable_dict['type']:
                return variable_dict['type']
            
            # Try to infer from init value
            if 'init' in variable_dict:
                init_val = variable_dict['init']
                # Check if it's a boolean
                if isinstance(init_val, bool):
                    return 'BOOL'
                # Check if it's a string representation of TRUE/FALSE
                if isinstance(init_val, str) and init_val.upper() in ('TRUE', 'FALSE'):
                    return 'BOOL'
                # Check if it's a float
                if isinstance(init_val, float):
                    return 'REAL'
                # Check if it's an integer (but not boolean)
                if isinstance(init_val, int) and not isinstance(init_val, bool):
                    return 'INT'
                # Try to parse as number
                try:
                    if '.' in str(init_val):
                        float(init_val)
                        return 'REAL'
                    else:
                        int(init_val)
                        return 'INT'
                except (ValueError, TypeError):
                    pass
            
            # Try to infer from 'value' field (alternative naming)
            if 'value' in variable_dict:
                val = variable_dict['value']
                if isinstance(val, bool):
                    return 'BOOL'
                if isinstance(val, str) and val.upper() in ('TRUE', 'FALSE'):
                    return 'BOOL'
                if isinstance(val, float):
                    return 'REAL'
                if isinstance(val, int) and not isinstance(val, bool):
                    return 'INT'
                try:
                    if '.' in str(val):
                        float(val)
                        return 'REAL'
                    else:
                        int(val)
                        return 'INT'
                except (ValueError, TypeError):
                    pass
        
        # If it's a plain string variable, check naming patterns
        if var_name:
            var_name_lower = var_name.lower()
            # Common BOOL variable patterns
            if any(pattern in var_name_lower for pattern in ['q', 'enabled', 'active', 'flag', 'is_', 'has_', 'error', 'status']):
                return 'BOOL'
            # Common REAL variable patterns
            if any(pattern in var_name_lower for pattern in ['temperature', 'pressure', 'voltage', 'current', 'flow', 'speed', 'position', 'time', 'distance', 'weight', 'value', 'margin', 'log_']):
                return 'REAL'
        
        # Default to INT for numeric variables
        return 'INT'

    def _get_variable_init_value(self, variable_dict, var_type):
        """
        Get the initial value for a variable based on its type.
        """
        if isinstance(variable_dict, dict):
            # Explicit init value provided
            if 'init' in variable_dict:
                init_val = variable_dict['init']
                if var_type == 'BOOL':
                    if isinstance(init_val, bool):
                        return 'TRUE' if init_val else 'FALSE'
                    elif isinstance(init_val, str) and init_val.upper() in ('TRUE', 'FALSE'):
                        return init_val.upper()
                    else:
                        return 'FALSE'
                else:
                    return str(init_val)
            
            if 'value' in variable_dict:
                val = variable_dict['value']
                if var_type == 'BOOL':
                    if isinstance(val, bool):
                        return 'TRUE' if val else 'FALSE'
                    elif isinstance(val, str) and val.upper() in ('TRUE', 'FALSE'):
                        return val.upper()
                    else:
                        return 'FALSE'
                else:
                    return str(val)
        
        # Default init values based on type
        if var_type == 'BOOL':
            return 'FALSE'
        elif var_type in ('INT', 'DINT'):
            return '0'
        elif var_type == 'REAL':
            return '0.0'
        else:
            return '0'

    def _translate_guard(self, guard):
        """Translate guard expressions from Python-style to MATIEC/IEC ST syntax."""
        expr = str(guard).strip() if guard is not None else ""
        if not expr:
            return "TRUE"
        
        expr = expr.replace("&&", " AND ").replace("||", " OR ")
        expr = expr.replace("!=", "<>")
        expr = expr.replace("==", "=")
        expr = re.sub(r"\bnot\b", "NOT", expr, flags=re.IGNORECASE)
        expr = re.sub(r"\band\b", "AND", expr, flags=re.IGNORECASE)
        expr = re.sub(r"\bor\b", "OR", expr, flags=re.IGNORECASE)
        expr = re.sub(r"\btrue\b", "TRUE", expr, flags=re.IGNORECASE)
        expr = re.sub(r"\bfalse\b", "FALSE", expr, flags=re.IGNORECASE)
        return expr
    
    def _generate_st(self, sfc_data, output_lines):
        """
        Generate ST code from SFC data (baseline or upgraded).
        Appends to output_lines list.
        """
        L = output_lines
        steps = sfc_data.get('steps', [])
        transitions = sfc_data.get('transitions', [])
        variables = sfc_data.get('variables', [])
        initial_step = sfc_data.get('initial_step', None)
        
        L.append("PROGRAM SFC_Program")
        L.append("(* Auto-generated by SFCJSONConverter *)")
        L.append("")
        L.append("VAR")
        
        # Step flags
        for s in steps:
            step_name = s.get('name', 'UNKNOWN') if isinstance(s, dict) else str(s)
            L.append("  {}_active : BOOL := FALSE;".format(step_name))
        
        # User variables
        for v in variables:
            if isinstance(v, dict):
                vname = v.get('name', str(v))
                # Infer type based on init value or name
                vtype = self._infer_variable_type(v, vname)
            else:
                vname = str(v)
                # For plain strings, infer type from variable name
                vtype = self._infer_variable_type(None, vname)
            
            # Get proper initial value for the inferred type
            init = self._get_variable_init_value(v, vtype)
            L.append("  {} : {} := {};".format(vname, vtype, init))
        
        L.append("END_VAR")
        L.append("")
        
        # Initialize initial step
        L.append("(* --- Initialize initial step --- *)")
        L.append("IF NOT {}_active THEN".format(initial_step))
        L.append("  {}_active := TRUE;".format(initial_step))
        L.append("END_IF;")
        L.append("")
        
        # Step actions
        L.append("(* --- Step actions --- *)")
        for s in steps:
            if isinstance(s, dict):
                step_name = s.get('name', 'UNKNOWN')
                step_func = s.get('function', '').strip()
            else:
                step_name = str(s)
                step_func = ''
            
            if step_func:
                L.append("IF {}_active THEN".format(step_name))
                L.append("  {};".format(step_func))
                L.append("END_IF;")
        
        L.append("")
        
        # Transitions
        L.append("(* --- Transitions --- *)")
        for t in transitions:
            src = t.get('src', 'UNKNOWN')
            tgt = t.get('tgt', 'UNKNOWN')
            guard = self._translate_guard(t.get('guard', 'TRUE'))
            
            L.append("IF {}_active AND ({}) THEN".format(src, guard))
            L.append("  {}_active := FALSE;".format(src))
            L.append("  {}_active := TRUE;".format(tgt))
            L.append("END_IF;")
        
        L.append("")
        L.append("END_PROGRAM")
    
    def generate(self):
        """
        Generate ST code for both baseline and upgraded SFC definitions.
        """
        print("\n  [STEP 2] Generating ST code for both baseline and upgraded ...")
        
        self.baseline_st_lines.clear()
        self.upgraded_st_lines.clear()
        
        self._generate_st(self.baseline_sfc, self.baseline_st_lines)
        self._generate_st(self.upgraded_sfc, self.upgraded_st_lines)
        
        print("    Baseline ST : {} lines generated.".format(len(self.baseline_st_lines)))
        print("    Upgraded ST : {} lines generated.".format(len(self.upgraded_st_lines)))
    
    def save(self, baseline_out, upgraded_out):
        """
        Save both baseline and upgraded ST files.
        """
        print("\n  [STEP 3] Saving : {}...  ".format(baseline_out), end="")
        baseline_ok = codegenutil.savefile(baseline_out, "\n".join(self.baseline_st_lines))
        
        print("\n  [STEP 3] Saving : {}".format(upgraded_out))
        upgraded_ok = codegenutil.savefile(upgraded_out, "\n".join(self.upgraded_st_lines))
        
        return baseline_ok and upgraded_ok
    
    def compile(self, baseline_st_file, upgraded_st_file):
        """
        Compile both ST files using iec2iec (or MATIEC).
        Returns (baseline_ok, baseline_msg, upgraded_ok, upgraded_msg)
        """
        print("\n  [STEP 4] Compiling both ST files with iec2iec ...")
        
        def compile_file(st_file, label):
            """Compile a single ST file."""
            print("\n    Compiling {} : {}".format(label, st_file))
            result = subprocess.run(
                ["make", "-f", "compile_st.mk", "SRC={}".format(st_file)],
                capture_output=True,
                text=True,
                timeout=30
            )
            
            if result.returncode == 0:
                return True, "Compilation successful."
            else:
                err = result.stderr.strip() or result.stdout.strip()
                return False, err
        
        baseline_ok, baseline_msg = compile_file(baseline_st_file, "BASELINE")
        upgraded_ok, upgraded_msg = compile_file(upgraded_st_file, "UPGRADED")
        
        return baseline_ok, baseline_msg, upgraded_ok, upgraded_msg
    
    def run(self, baseline_out=None, upgraded_out=None):
        """
        Full pipeline: parse JSON, generate ST files, save them, and compile.
        Returns a result dictionary for batch processing.
        """
        result = {
            "json_file"   : self.json_file,
            "baseline_steps"      : 0,
            "baseline_transitions": 0,
            "baseline_variables"  : 0,
            "upgraded_steps"      : 0,
            "upgraded_transitions": 0,
            "upgraded_variables"  : 0,
            "baseline_st_file"    : "",
            "upgraded_st_file"    : "",
            "status"     : "",
            "message"    : "",
            "timestamp"  : datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        }
        
        parse_ok = self.parse()
        if not parse_ok:
            result.update(status="FAILED", message="Parse error")
            return result
        
        result["baseline_steps"]       = len(self.baseline_sfc.get('steps', []))
        result["baseline_transitions"] = len(self.baseline_sfc.get('transitions', []))
        result["baseline_variables"]   = len(self.baseline_sfc.get('variables', []))
        result["upgraded_steps"]       = len(self.upgraded_sfc.get('steps', []))
        result["upgraded_transitions"] = len(self.upgraded_sfc.get('transitions', []))
        result["upgraded_variables"]   = len(self.upgraded_sfc.get('variables', []))
        
        self.generate()
        
        if baseline_out is None:
            base = os.path.splitext(self.json_file)[0]
            baseline_out = base + "_baseline.st"
            upgraded_out = base + "_upgraded.st"
        
        result["baseline_st_file"] = baseline_out
        result["upgraded_st_file"] = upgraded_out
        
        if not self.save(baseline_out, upgraded_out):
            result.update(status="FAILED", message="Save error")
            return result
        
        b_ok, b_msg, u_ok, u_msg = self.compile(baseline_out, upgraded_out)
        
        result["status"] = "SUCCESS" if (b_ok and u_ok) else "FAILED"
        result["message"] = "Baseline: {}\nUpgraded: {}".format(
            "OK" if b_ok else "FAILED - {}".format(b_msg),
            "OK" if u_ok else "FAILED - {}".format(u_msg)
        )
        
        # Console final banner per file
        if not (b_ok and u_ok):
            print("  DETAILS  :\n{}".format(result["message"]))
        
        return result


#  Batch runner for JSON files                                          #

def run_batch_json(json_files, txt_report="json_batch_report.txt"):
    all_results = []
    total = len(json_files)

    print("\n" + "" + ""*58 + "")
    print("{:^58}".format("JSON SFC MATIEC Batch Converter"))
    print("{:^58}".format("Total files : {}".format(total)))
    print("" + ""*58 + "")

    for idx, json_file in enumerate(json_files, start=1):
        print("\n" + ""*60)
        print("  [{}/{}]  {}".format(idx, total, json_file))
        print(""*60)

        if not os.path.exists(json_file):
            print("  [ERROR] File not found: {}".format(json_file))
            all_results.append({
                "json_file"   : json_file,
                "baseline_steps"      : 0,
                "baseline_transitions": 0,
                "baseline_variables"  : 0,
                "upgraded_steps"      : 0,
                "upgraded_transitions": 0,
                "upgraded_variables"  : 0,
                "baseline_st_file"    : "",
                "upgraded_st_file"    : "",
                "status"     : "FAILED",
                "message"    : "File not found",
                "timestamp"  : datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            })
            continue

        converter = SFCJSONConverter(json_file)
        result    = converter.run()
        all_results.append(result)

    # â"€â"€ Console summary â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€ #
    successes = sum(1 for r in all_results if r["status"] == "SUCCESS")
    failures  = len(all_results) - successes

    print("\n" + "" + ""*58 + "")
    print("{:^58}".format("BATCH  SUMMARY"))
    print(" " + " "*58 + "")
    print("  {:<22} {:>32}".format("Total Files :",  total))
    print("  {:<22} {:>32}".format("Succeeded   :",  successes))
    print("  {:<22} {:>32}".format("Failed      :",  failures))
    print(" " + ""*58 + "")
    print("  {:<5} {:<28} {:>6}".format(
        "#", "JSON File", "Status"))
    print(" " + " "*58 + " ")
    for r in all_results:
        icon = "[OK]  " if r["status"] == "SUCCESS" else "[FAIL]"
        name = os.path.basename(r["json_file"])[:27]
        print("  {:<5} {:<28} {:>6}".format(
            all_results.index(r)+1, name, icon))
    print(" " + " "*58 + " ")

    return all_results


def main_json():
    """Entry point for JSON-based batch conversion."""
    if len(sys.argv) < 2:
        print("""
Usage (multiple files):
  python sfc_converter.py file1.json file2.json file3.json

Usage (folder – processes all .json SFC files inside):
  python sfc_converter.py --folder /path/to/json_files/

Optional: specify report output name (default: json_batch_report.txt)
  python sfc_converter.py file1.json file2.json --report my_report.txt

JSON File Format:
  {{
    "id": "...",
    "sfc_baseline": {{
      "steps": [...],
      "transitions": [...],
      "variables": [...],
      "initial_step": "..."
    }},
    "sfc_upgraded": {{
      "steps": [...],
      "transitions": [...],
      "variables": [...],
      "initial_step": "..."
    }}
  }}
""")
        sys.exit(1)

    args      = sys.argv[1:]
    txt_name  = "json_batch_report.txt"
    json_files = []

    # Parse --report flag
    if "--report" in args:
        idx      = args.index("--report")
        txt_name = args[idx + 1]
        args     = [a for i, a in enumerate(args) if i not in (idx, idx+1)]

    # Parse --folder flag
    if "--folder" in args:
        idx    = args.index("--folder")
        folder = args[idx + 1]
        if not os.path.isdir(folder):
            print("[ERROR] Folder not found: {}".format(folder))
            sys.exit(1)
        json_files = codegenutil.readfiles(folder)  # Recursively reads files from folder
        if not json_files:
            print("[ERROR] No .json SFC files found in: {}".format(folder))
            sys.exit(1)
    else:
        json_files = args

    run_batch_json(json_files, txt_name)
    sys.exit(0)


if __name__ == "__main__":
    main()
